### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by scienceaiden** [traversc/cox-nnet#1]
Hello,
Hope all is well.
My env is Windows 10, python 3.6, cox-nnet 0.202

Anaconda gave this error:

![image](https://user-images.githubusercontent.com/25181661/30938158-1e5bd108-a3a7-11e7-9504-12bd6bf311ec.png)

I was running the example from http://traversc.github.io/cox-nnet/docs/examples/#kirc-example.

Please advise

**Comment by traversc** [comment]
Hi, please try python 2 instead of python 3.

**Comment by scienceaiden** [comment]
sorry, did not help. what numpy version do you use?

**Comment by traversc** [comment]
I didn't remember which numpy version was used.  The RNG function does not coerce to integer any longer.  

Use the `simpleNetArch(x_train, n_nodes)` and add to the `model_params`.  Make sure it is integer, not float.

**Comment by scienceaiden** [comment]
i know rng does not return only integer but what do you mean "use simpleNetArch(x_train, n_nodes)"? i see you have it in the module but did not understand why

**Comment by scienceaiden** [comment]
this code should be changed from

` rng.uniform(
                    low=-numpy.sqrt(6. / (map[i][0] + map[i][2])),
                    high=numpy.sqrt(6. / (map[i][0] + map[i][2])),
                    size=(map[i][0], map[i][2])
                ),`
to

` rng.uniform(
                    low=-numpy.sqrt(6. / (map[i][0] + map[i][2])).astype(numpy.int),
                    high=numpy.sqrt(6. / (map[i][0] + map[i][2])).astype(numpy.int),
                    size=(map[i][0], map[i][2])
                ),`

by i am struggling with last line in order to convert to integer...

**Comment by traversc** [comment]
Sorry for the late response.  I added a simple fix to force an integer in github and tested it out.   Line 85: 

`                    size=(int(map[i][0]), int(map[i][2]))`

**Comment by scienceaiden** [comment]
thank you - after changing in other couple places, it is working perfectly
