### ISSUE TITLE
Running examples gives error - NameError: name 'L2CVProfile' is not defined

### ISSUE THREAD

**Issue by krish240574** [traversc/cox-nnet#2]
Hello, 
When I run the following - python test_PBC.py  inside /examples/- I get the following error - 
python test_PBC.py
Traceback (most recent call last):
  File "test_PBC.py", line 23, in <module>
    cv_likelihoods, L2_reg_params, mean_cvpl = L2CVProfile(x_train,ytime_train,ystatus_train,
NameError: name 'L2CVProfile' is not defined

I even tried a sys.path.append of the directory containing cox-nnet.py, no luck.

**Comment by traversc** [comment]
Hi, I'm not sure what could be the issue.  You can see that the function is defined on line 513.  You can try manually entering the python source file.

**Comment by quzhouxiachuan** [comment]
I have the same issue
