### ISSUE TITLE
Error message 2

### ISSUE THREAD

**Issue by mathildesautreuil** [traversc/cox-nnet#3]
Hello,

I have the same error message that scienceML (posted on September 2017, 27th). I tried to change code by adding "int" on line 85 as you suggested. But I have again the same error type: 
```
Traceback (most recent call last):
  File "<input>", line 28, in <module>
  File "/home/sautreuim/NNetCox/local/lib/python2.7/site-packages/cox_nnet/cox_nnet.py", line 540, in L2Profile
    model, cost_iter = trainCoxMlp(x_train = x_train, ytime_train = ytime_train, ystatus_train = ystatus_train, model_params = model_params, search_params = search_params, verbose=verbose)
  File "/home/sautreuim/NNetCox/local/lib/python2.7/site-packages/cox_nnet/cox_nnet.py", line 272, in trainCoxMlp
    model = CoxMlp(rng = rng, x_train=x_train, n_samples = N_train, node_map = node_map, input_split = input_split)
  File "/home/sautreuim/NNetCox/local/lib/python2.7/site-packages/cox_nnet/cox_nnet.py", line 160, in __init__
    activation=T.tanh
  File "/home/sautreuim/NNetCox/local/lib/python2.7/site-packages/cox_nnet/cox_nnet.py", line 85, in __init__
    size=(int(map[i][0]), int(map[i][2]))
  File "mtrand.pyx", line 1307, in mtrand.RandomState.uniform
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
TypeError: 'numpy.float64' object cannot be interpreted as an index
```
How can I resolve that ?

Thank you.

**Comment by Nadam0707** [comment]
I tried to run the code using the KIRC dataset, but encountered te following error, even after I used int(len(map) in the range statement.
 154         for i in range(len(self.node_map)):
--> 155             hidden_layer = HiddenLayer(
    156             rng=self.rng,
    157             input=self.input if i == 0 else self.hidden_list[i-1].output,

~\AppData\Local\Temp/ipykernel_31916/3351192275.py in __init__(self, rng, input, n_samples, map, label, activation)
     88             print("############# i=", i, len(map))
     89             W_values = numpy.asarray(
---> 90                 rng.uniform(
     91                     low=-numpy.sqrt(6. / (map[i][0] + map[i][2])),
     92                     high=numpy.sqrt(6. / (map[i][0] + map[i][2])),

mtrand.pyx in numpy.random.mtrand.RandomState.uniform()

_common.pyx in numpy.random._common.cont()

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by traversc** [comment]
Hello, given the age of this project and de-precation of `theano` I would suggest re-implementing in a modern framework. 

Best,
-T
