### ISSUE TITLE
Error Message - L2CVProfile not defined

### ISSUE THREAD

**Issue by rmaanyam** [traversc/cox-nnet#4]
Hi traversc!

I'm trying to run 'PBC' example given in the package docs [here](http://traversc.github.io/cox-nnet/docs/examples/)
..
However, got stuck when running the below code-snippet...with the following 'NameError' message...
However, I see the 'L2CVProfile' defined in the cox-nnet.py script file, though.
Unable to figure it out - am I missing something... 
Could you please help? 
Tried in both Windows and Linux(CentOS 7), with Python 3..
Appreciate anyone's guidance, please..

-----
#cross validate training set to determine lambda parameters
cv_likelihoods, L2_reg_params, mean_cvpl = L2CVProfile(x_train,ytime_train,ystatus_train,
    model_params,search_params,cv_params, verbose=False)
------------------

>>>    model_params = dict(node_map = None, input_split = None)
>>> search_params = dict(method = "nesterov", learning_rate=0.01, momentum=0.9,
...     max_iter=2000, stop_threshold=0.995, patience=1000, patience_incr=2, rand_seed = 123,
...     eval_step=23, lr_decay = 0.9, lr_growth = 1.0)
>>> cv_params = dict(cv_seed=1, n_folds=5, cv_metric = "loglikelihood",
...     L2_range = numpy.arange(-4.5,1,0.5))
>>> cv_likelihoods, L2_reg_params, mean_cvpl = L2CVProfile(x_train,ytime_train,ystatus_train,
...     model_params,search_params,cv_params, verbose=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

NameError: name 'L2CVProfile' is not defined
--------------------------------------------------------

**Comment by traversc** [comment]
Hi, you can find the function definition here: https://github.com/traversc/cox-nnet/blob/8e73a1145f7a6c1577f8a107120b0494571e8541/cox_nnet/cox_nnet.py

The version on pip may be outdated.  Many of these code used older version of packages (this project was finished many years ago), so may not work perfectly any more, but I think you can see what it is trying to do from the code and modify for your own purposes.  Good luck!
