### ISSUE TITLE
search for parameters

### ISSUE THREAD

**Issue by quzhouxiachuan** [traversc/cox-nnet#5]
Hi Traverse, 
Thanks for providing a great tool for performing deep learning based survival model. This is not really an issue but I am wondering if cox-nnet able to search for other parameters except for L2? For example, can I specify a range of numbers for learning rate (e.g. [0.1,0.01, 0.001]) or neurons [8,32,62]?

**Comment by traversc** [comment]
You would need to modify the code to search those other parameters.
