### ISSUE TITLE
node_map

### ISSUE THREAD

**Issue by quzhouxiachuan** [traversc/cox-nnet#6]
Hi Traversc, 
Thank you for providing the code. I try to design a NN with 2 hidden layers. I looked up how to define node_map. Your document says: node_map defines the connections of the input layer (or sub-input layers). node_map list of list of triples (one list for each hidden layer). A triple defines the inputs of a sub-hidden layer and how many output nodes it has. I.e., ( # of input neurons, list of input sub-layers, # of output neurons). The simpleNetArch function can be used to generate an architecture with a given number of hidden layer neurons.

It is hard to understand the structure abstractly. Could you give an example of what a 2 hidden layer node_map looks like? Also, why do we need input_split?

**Comment by traversc** [comment]
You can think of the input of the 2nd hidden layer as the output of the first hidden layer.  So You will have two triples in a list.  It has been a while since so you could take a look at the HiddenLayer class to get a better idea of how it is used.

**Comment by quzhouxiachuan** [comment]
Thank you for your reply! Does this look right? for example, [(3,4,5),(5,4,6)]? I will also check HiddenLayer class.

**Comment by quzhouxiachuan** [comment]
I tried format like this: [[(7,[0],3)], [(3,[0],9)]] and it worked. I assume the second element in the tuple is set as 0 if there is no input_split?
